using System;
using System.Collections.Generic;
using System.Text;
using Newtonsoft.Json;

namespace KodKod.Runtime
{
    public class Problem
    {
        // A URI reference [RFC3986] that identifies the problem type.This specification encourages that, when
        // dereferenced, it provide human-readable documentation for the problem type
        // (e.g., using HTML [W3C.REC-html5-20141028]).  When this member is not present, its value is assumed to be
        // "about:blank".
        [JsonProperty("type")]
        public string Type { get; set; }

        //  A short, human-readable summary of the problem type.It SHOULD NOT change from occurrence to occurrence
        // of the problem, except for purposes of localization(e.g., using proactive content negotiation; 
        // see[RFC7231], Section 3.4).
        [JsonProperty("title")]
        public string Title { get; set; }

        // The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public int? Status { get; set; }

        // A human-readable explanation specific to this occurrence of the problem.
        [JsonProperty("detail")]
        public string Detail { get; set; }

        // A URI reference that identifies the specific occurrence of the problem.It may or may not yield further
        // information if dereferenced."
        [JsonProperty("instance")]
        public string Instance { get; set; }
    }
}
